package panel;

import java.util.List;
import model.CategorieProdotti;
import model.Varianti;

/**
 *
 * @author Stefano
 */
public class jpVarianti extends javax.swing.JPanel {

    List<Varianti> varianti;
    CategorieProdotti categoriaProdotto;

    /**
     *
     * @param varianti
     */
    public jpVarianti(List<Varianti> varianti) {
        this.varianti = varianti;
        categoriaProdotto = null;
        Setup();
        initComponents();
    }

    /**
     * 
     * @param varianti
     * @param categoriaProdotto 
     */
    public jpVarianti(List<Varianti> varianti, CategorieProdotti categoriaProdotto) {
        this.varianti = varianti;
        this.categoriaProdotto = categoriaProdotto;
        Setup();
        initComponents();
    }

    /**
     *
     */
    private void Setup() {
        jCmbVarianti.removeAllItems();

        for (Varianti variante : varianti) {
            if (categoriaProdotto == null || variante.getCategoriaProdotto().getId().equals(categoriaProdotto.getId())) {
                jCmbVarianti.addItem(variante.toString());
            }

            jCmbVarianti.setSelectedItem(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCmbVarianti = new javax.swing.JComboBox();
        jTextVariante = new javax.swing.JTextField();
        jBtnOk = new javax.swing.JButton();

        jCmbVarianti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnOk.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnOk)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCmbVarianti, 0, 158, Short.MAX_VALUE)
                        .addComponent(jTextVariante)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCmbVarianti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextVariante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBtnOk)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnOk;
    private javax.swing.JComboBox jCmbVarianti;
    private javax.swing.JTextField jTextVariante;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the varianti
     */
    public List<Varianti> getVarianti() {
        return varianti;
    }

    /**
     * @param varianti the varianti to set
     */
    public void setVarianti(List<Varianti> varianti) {
        this.varianti = varianti;
    }

    /**
     * @return the categoriaProdotto
     */
    public CategorieProdotti getCategoriaProdotto() {
        return categoriaProdotto;
    }

    /**
     * @param categoriaProdotto the categoriaProdotto to set
     */
    public void setCategoriaProdotto(CategorieProdotti categoriaProdotto) {
        this.categoriaProdotto = categoriaProdotto;
    }
}
